name: Python CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"] # Test against multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Sets up the specified Python version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Installs dependencies from  requirements.txt

    - name: Run Pytest
      run: |
        pytest # Execute your tests with pytest
      
